name: intents-data-aggregator

services:
  redis:
    image: redis:7-alpine
    container_name: intents-data-aggregator-redis
    ports:
      - "6379:6379"
    volumes:
      - intents-data-aggregator_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  intents-data-aggregator_redis_data: